In [50]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers as ly
import pandas as pd

In [51]:
data = tf.keras.datasets.mnist

In [52]:
(train_images,train_out), (test_images,test_out) = data.load_data()

In [53]:
(train_images,test_images) = train_images/255.0 , test_images/255.0


In [54]:
train_out, test_out = pd.get_dummies(train_out).values,pd.get_dummies(test_out).values
print (train_out)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [92]:
model = tf.keras.models.Sequential()
model.add(ly.Flatten(input_shape=(28,28)))
model.add(ly.Dense(512,activation='relu'))
model.add(ly.Dropout(0.2))
model.add(ly.Dense(256,activation='relu'))
model.add(ly.Dropout(0.2))
model.add(ly.Dense(64,activation='relu'))
# model.add(ly.Dropout(0.1))
model.add(ly.Dense(10,activation=tf.nn.softmax))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()
          

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_26 (Flatten)         (None, 784)               0         
_________________________________________________________________
dense_78 (Dense)             (None, 512)               401920    
_________________________________________________________________
dropout_25 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_79 (Dense)             (None, 256)               131328    
_________________________________________________________________
dropout_26 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_80 (Dense)             (None, 64)                16448     
_________________________________________________________________
dense_81 (Dense)             (None, 10)                650       
Total para

In [93]:
model.fit(train_images,train_out,validation_split=0.2,batch_size = 128, epochs=50)

Train on 48000 samples, validate on 12000 samples
Epoch 1/50
48000/48000 [==============================] - 9s 186us/step - loss: 0.3140 - acc: 0.9036 - val_loss: 0.1259 - val_acc: 0.9616
Epoch 2/50
48000/48000 [==============================] - 8s 167us/step - loss: 0.1206 - acc: 0.9633 - val_loss: 0.1059 - val_acc: 0.9678
Epoch 3/50
48000/48000 [==============================] - 8s 158us/step - loss: 0.0881 - acc: 0.9725 - val_loss: 0.0800 - val_acc: 0.9757
Epoch 4/50
48000/48000 [==============================] - 8s 160us/step - loss: 0.0685 - acc: 0.9792 - val_loss: 0.0819 - val_acc: 0.9758
Epoch 5/50
48000/48000 [==============================] - 8s 161us/step - loss: 0.0527 - acc: 0.9835 - val_loss: 0.0830 - val_acc: 0.9761
Epoch 6/50
48000/48000 [==============================] - 8s 161us/step - loss: 0.0472 - acc: 0.9847 - val_loss: 0.0813 - val_acc: 0.9772
Epoch 7/50
48000/48000 [==============================] - 8s 169us/step - loss: 0.0426 - acc: 0.9858 - val_loss: 0.0793 - 

In [94]:
model.evaluate(test_images,test_out)

10000/10000 [==============================] - 1s 105us/step


[0.09865030846275635, 0.9835]